export const PRODUCTADDED = 'PRODUCTADDED';
export const ADDTOCART = 'ADDTOCART';
export const GETUSERCART = 'GETUSERCART';
export const EMPTYCART = 'EMPTYCART';

export const DELETEITEM = 'DELETEITEM';
